/* jshint esversion: 6 */

const buildMatrix = (width, height) => {
  const matrix = [];
  let count = 1;
  for (let i = 0; i < height; i++) {
    let row = [];
    for (let j = 0; j < width; j++) {
      row.push(count++);
    }
    matrix.push(row);
  }
  return matrix;
};

exports.matrix = {
  oneByOne     : buildMatrix(1,1),
  oneByTwo     : buildMatrix(1,2),
  oneByThree   : buildMatrix(1,3),
  oneByFour    : buildMatrix(1,4),
  oneByFive    : buildMatrix(1,5),

  twoByOne     : buildMatrix(2,1),
  twoByTwo     : buildMatrix(2,2),
  twoByThree   : buildMatrix(2,3),
  twoByFour    : buildMatrix(2,4),
  twoByFive    : buildMatrix(2,5),

  threeByOne   : buildMatrix(3,1),
  threeByTwo   : buildMatrix(3,2),
  threeByThree : buildMatrix(3,3),
  threeByFour  : buildMatrix(3,4),
  threeByFive  : buildMatrix(3,5),

  fourByOne    : buildMatrix(4,1),
  fourByTwo    : buildMatrix(4,2),
  fourByThree  : buildMatrix(4,3),
  fourByFour   : buildMatrix(4,4),
  fourByFive   : buildMatrix(4,5),

  fiveByOne    : buildMatrix(5,1),
  fiveByTwo    : buildMatrix(5,2),
  fiveByThree  : buildMatrix(5,3),
  fiveByFour   : buildMatrix(5,4),
  fiveByFive   : buildMatrix(5,5),
};

exports.answer = {
  oneByOne     : [[1]],

  oneByTwo     : [[2],
                  [1]],

  oneByThree   : [[3],
                  [2],
                  [1]],

  oneByFour    : [[4],
                  [3],
                  [2],
                  [1]],

  oneByFive    : [[5],
                  [4],
                  [3],
                  [2],
                  [1]],

  twoByOne     : [[1],
                  [2]],

  twoByTwo     : [[3],
                  [1,4],
                  [2],
                  [1],
                  [2,3],
                  [4]],

  twoByThree   : [[5],
                  [3,6],
                  [1,4],
                  [2],
                  [1],
                  [2,3],
                  [4,5],
                  [6]],

  twoByFour    : [[7],
                  [5,8],
                  [3,6],
                  [1,4],
                  [2],
                  [1],
                  [2,3],
                  [4,5],
                  [6,7],
                  [8]],

  twoByFive    : [[9],
                  [7,10],
                  [5,8],
                  [3,6],
                  [1,4],
                  [2],
                  [1],
                  [2,3],
                  [4,5],
                  [6,7],
                  [8,9],
                  [10]],

  threeByOne   : [[1],
                  [2],
                  [3]],

  threeByTwo   : [[4],
                  [1,5],
                  [2,6],
                  [3],
                  [1],
                  [2,4],
                  [3,5],
                  [6]],

  threeByThree : [[7],
                  [4,8],
                  [1,5,9],
                  [2,6],
                  [3],
                  [1],
                  [2,4],
                  [3,5,7],
                  [6,8],
                  [9]],

  threeByFour  : [[10],
                  [7,11],
                  [4,8,12],
                  [1,5,9],
                  [2,6],
                  [3],
                  [1],
                  [2,4],
                  [3,5,7],
                  [6,8,10],
                  [9,11],
                  [12]],

  threeByFive  : [[13],
                  [10,14],
                  [7,11,15],
                  [4,8,12],
                  [1,5,9],
                  [2,6],
                  [3],
                  [1],
                  [2,4],
                  [3,5,7],
                  [6,8,10],
                  [9,11,13],
                  [12,14],
                  [15]],

  fourByOne    : [[1],
                  [2],
                  [3],
                  [4]],

  fourByTwo    : [[5],
                  [1,6],
                  [2,7],
                  [3,8],
                  [4],
                  [1],
                  [2,5],
                  [3,6],
                  [4,7],
                  [8]],

  fourByThree  : [[9],
                  [5,10],
                  [1,6,11],
                  [2,7,12],
                  [3,8],
                  [4],
                  [1],
                  [2,5],
                  [3,6,9],
                  [4,7,10],
                  [8,11],
                  [12]],

  fourByFour   : [[13],
                  [9,14],
                  [5,10,15],
                  [1,6,11,16],
                  [2,7,12],
                  [3,8],
                  [4],
                  [1],
                  [2,5],
                  [3,6,9],
                  [4,7,10,13],
                  [8,11,14],
                  [12,15],
                  [16]],

  fourByFive   : [[17],
                  [13,18],
                  [9,14,19],
                  [5,10,15,20],
                  [1,6,11,16],
                  [2,7,12],
                  [3,8],
                  [4],
                  [1],
                  [2,5],
                  [3,6,9],
                  [4,7,10,13],
                  [8,11,14,17],
                  [12,15,18],
                  [16,19],
                  [20]],

  fiveByOne    : [[1],
                  [2],
                  [3],
                  [4],
                  [5]],

  fiveByTwo    : [[6],
                  [1,7],
                  [2,8],
                  [3,9],
                  [4,10],
                  [5],
                  [1],
                  [2,6],
                  [3,7],
                  [4,8],
                  [5,9],
                  [10]],

  fiveByThree  : [[11],
                  [6,12],
                  [1,7,13],
                  [2,8,14],
                  [3,9,15],
                  [4,10],
                  [5],
                  [1],
                  [2,6],
                  [3,7,11],
                  [4,8,12],
                  [5,9,13],
                  [10,14],
                  [15]],

  fiveByFour   : [[16],
                  [11,17],
                  [6,12,18],
                  [1,7,13,19],
                  [2,8,14,20],
                  [3,9,15],
                  [4,10],
                  [5],
                  [1],
                  [2,6],
                  [3,7,11],
                  [4,8,12,16],
                  [5,9,13,17],
                  [10,14,18],
                  [15,19],
                  [20]],

  fiveByFive   : [[21],
                  [16,22],
                  [11,17,23],
                  [6,12,18,24],
                  [1,7,13,19,25],
                  [2,8,14,20],
                  [3,9,15],
                  [4,10],
                  [5],
                  [1],
                  [2,6],
                  [3,7,11],
                  [4,8,12,16],
                  [5,9,13,17,21],
                  [10,14,18,22],
                  [15,19,23],
                  [20,24],
                  [25]]
};
